# Generated by Django 5.1.5 on 2025-03-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='credit_score',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
